version: '3.8'

services:
  survival-server:
    build:
      context: .
      dockerfile: ./prod/Dockerfiles/mindustry.Dockerfile
    init: true
    tty: true
    stdin_open: true
    stop_signal: SIGTERM
    stop_grace_period: 15s
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    volumes:
      - ./prod/maps/:/app/config/maps/
    networks:
      - plague
    environment:
      PORT: 6567
    healthcheck:
      test: [ 'CMD-SHELL', 'ss -ltu | grep $$PORT | wc -l | grep 2' ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 1m
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

networks:
  plague: