services:
  server:
    build:
      context: .
      dockerfile: ./prod/Dockerfiles/mindustry.Dockerfile
    init: true
    tty: true
    stdin_open: true
    stop_signal: SIGTERM
    stop_grace_period: 15s
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    volumes:
      - ./prod/maps/:/app/config/maps/
      - ./prod/config.alex:/app/config/mods/config.alex
      - ./prod/AlexServerPlugin.jar:/app/config/mods/AlexServerPlugin.jar
    networks:
      - plague
    environment:
      PORT: 6567
    healthcheck:
      test: [ 'CMD-SHELL', 'ss -ltu | grep $$PORT | wc -l | grep 2' ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 1m
    restart: unless-stopped
    mem_limit: 2G
    cpus: 2

  portainer:
    image: portainer/portainer-ce:2.19.4-alpine
    init: true
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - plague
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '0.5'

volumes:
  portainer-data:

networks:
  plague: